[2024-04-15T17:01:57.587+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:01:54.905972+00:00 [queued]>
[2024-04-15T17:01:57.593+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:01:54.905972+00:00 [queued]>
[2024-04-15T17:01:57.593+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-04-15T17:01:57.608+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2024-04-15 17:01:54.905972+00:00
[2024-04-15T17:01:57.615+0000] {standard_task_runner.py:60} INFO - Started process 5886 to run task
[2024-04-15T17:01:57.618+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_visualization', 'generate_visualizations', 'manual__2024-04-15T17:01:54.905972+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/dbt_visualization.py', '--cfg-path', '/tmp/tmpzb8y__49']
[2024-04-15T17:01:57.620+0000] {standard_task_runner.py:88} INFO - Job 118: Subtask generate_visualizations
[2024-04-15T17:01:57.660+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T17:01:54.905972+00:00 [running]> on host ec3d883e7b78
[2024-04-15T17:01:57.735+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_visualization' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T17:01:54.905972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T17:01:54.905972+00:00'
[2024-04-15T17:01:57.743+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-15T17:01:57.754+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dbt_visualization.py:28 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-15T17:01:57.814+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-15T17:01:58.133+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-15T17:01:58.144+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dbt_visualization, task_id=generate_visualizations, execution_date=20240415T170154, start_date=20240415T170157, end_date=20240415T170158
[2024-04-15T17:01:58.190+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T17:01:58.208+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
