[2024-04-14T16:00:31.592+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T15:55:16.775646+00:00 [queued]>
[2024-04-14T16:00:31.598+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T15:55:16.775646+00:00 [queued]>
[2024-04-14T16:00:31.598+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-04-14T16:00:31.615+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_reddit_data> on 2024-04-14 15:55:16.775646+00:00
[2024-04-14T16:00:31.624+0000] {standard_task_runner.py:60} INFO - Started process 1281 to run task
[2024-04-14T16:00:31.627+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'reddit_api_dag', 'get_reddit_data', 'manual__2024-04-14T15:55:16.775646+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/reddit_api_dag.py', '--cfg-path', '/tmp/tmps5e9yf47']
[2024-04-14T16:00:31.628+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask get_reddit_data
[2024-04-14T16:00:31.668+0000] {task_command.py:423} INFO - Running <TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T15:55:16.775646+00:00 [running]> on host f383f10413fd
[2024-04-14T16:00:31.745+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='reddit_api_dag' AIRFLOW_CTX_TASK_ID='get_reddit_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T15:55:16.775646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T15:55:16.775646+00:00'
[2024-04-14T16:00:31.748+0000] {warnings.py:109} WARNING - /opt/***/dags/reddit_api_dag.py:61: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  pg_hook = PostgresHook(

[2024-04-14T16:00:31.755+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-14T16:00:34.196+0000] {logging_mixin.py:188} INFO - title: Facts
[2024-04-14T16:00:34.197+0000] {logging_mixin.py:188} INFO - title: "We have great datasets"
[2024-04-14T16:00:34.197+0000] {logging_mixin.py:188} INFO - title: i just want sleep
[2024-04-14T16:00:34.198+0000] {logging_mixin.py:188} INFO - title: I've finally built the perfect data pipeline!
[2024-04-14T16:00:34.198+0000] {logging_mixin.py:188} INFO - title: PSA: Learn Vendor Agnostic Technologies!
[2024-04-14T16:00:34.199+0000] {logging_mixin.py:188} INFO - title: Had an onsite interview with one of FAANG, all 6 interviewers were Indian 
[2024-04-14T16:00:34.199+0000] {logging_mixin.py:188} INFO - title: The data engineer came to me... tears in his eyes
[2024-04-14T16:00:34.199+0000] {logging_mixin.py:188} INFO - title: Exporting to excel is always a people pleaser...
[2024-04-14T16:00:34.200+0000] {logging_mixin.py:188} INFO - title: It’s happening guys
[2024-04-14T16:00:34.200+0000] {logging_mixin.py:188} INFO - title: 2022 Mood
[2024-04-14T16:00:34.201+0000] {logging_mixin.py:188} INFO - title: Data driven organisations
[2024-04-14T16:00:34.201+0000] {logging_mixin.py:188} INFO - title: Is this chart accurate?
[2024-04-14T16:00:34.201+0000] {logging_mixin.py:188} INFO - title: Who owns data quality?
[2024-04-14T16:00:34.202+0000] {logging_mixin.py:188} INFO - title: How true is this!
[2024-04-14T16:00:34.202+0000] {logging_mixin.py:188} INFO - title: DataEngineering 2021 in one pic
[2024-04-14T16:00:34.203+0000] {logging_mixin.py:188} INFO - title: I wrote a children's book / illustrated guide to Apache Kafka
[2024-04-14T16:00:34.203+0000] {logging_mixin.py:188} INFO - title: I’ve had the definition wrong this entire time…
[2024-04-14T16:00:34.204+0000] {logging_mixin.py:188} INFO - title: I've been a big data engineer since 2015. I've worked at FAANG for 6 years and grew from L3 to L6. AMA
[2024-04-14T16:00:34.204+0000] {logging_mixin.py:188} INFO - title: Data Scientists -- Ok, now I get it.
[2024-04-14T16:00:35.951+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_api_dag.py", line 33, in _get_reddit_data
    _save_to_database(top_posts)
  File "/opt/airflow/dags/reddit_api_dag.py", line 78, in _save_to_database
    post.author_fullname,
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/base.py", line 36, in __getattr__
    return getattr(self, attribute)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/base.py", line 37, in __getattr__
    raise AttributeError(
AttributeError: 'Submission' object has no attribute 'author_fullname'
[2024-04-14T16:00:35.959+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=reddit_api_dag, task_id=get_reddit_data, execution_date=20240414T155516, start_date=20240414T160031, end_date=20240414T160035
[2024-04-14T16:00:35.969+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-04-14T16:00:35.969+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-04-14T16:00:35.969+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-14T16:00:35.970+0000] {email.py:281} INFO - Sent an alert email to ['66130047@dpu.ac.th']
[2024-04-14T16:00:35.989+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task get_reddit_data ('Submission' object has no attribute 'author_fullname'; 1281)
[2024-04-14T16:00:36.009+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T16:00:36.032+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
