[2024-04-14T15:40:31.768+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T14:22:58.929834+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
