[2024-04-15T16:51:49.396+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T16:45:54.206864+00:00 [queued]>
[2024-04-15T16:51:49.402+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T16:45:54.206864+00:00 [queued]>
[2024-04-15T16:51:49.402+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2024-04-15T16:51:49.418+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2024-04-15 16:45:54.206864+00:00
[2024-04-15T16:51:49.424+0000] {standard_task_runner.py:60} INFO - Started process 5057 to run task
[2024-04-15T16:51:49.427+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_visualization', 'generate_visualizations', 'manual__2024-04-15T16:45:54.206864+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/dbt_visualization.py', '--cfg-path', '/tmp/tmpw7jv_0kx']
[2024-04-15T16:51:49.429+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask generate_visualizations
[2024-04-15T16:51:49.475+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_visualization.generate_visualizations manual__2024-04-15T16:45:54.206864+00:00 [running]> on host ec3d883e7b78
[2024-04-15T16:51:49.568+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_visualization' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T16:45:54.206864+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T16:45:54.206864+00:00'
[2024-04-15T16:51:49.577+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-15T16:51:49.588+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dbt_visualization.py:28 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-15T16:51:50.743+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-15T16:51:52.312+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-15T16:51:52.321+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dbt_visualization, task_id=generate_visualizations, execution_date=20240415T164554, start_date=20240415T165149, end_date=20240415T165152
[2024-04-15T16:51:52.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T16:51:52.390+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
